### ISSUE TITLE
Lost most of my OpenCalais categories - is this due to the Calais' linked data cloud shutdown?

### ISSUE THREAD

**Issue by geejaye** [ElusiveMind/opencalais#1]
Note - this is also a Drupal issue, here: https://projects.advantagelabs.com/issues/14399

I only have 3 Open Calais categories in the Open Calais tab now. A few weeks ago, though, I was getting a whole page of categories (and taxonomies).

Could this be related to the fact that Calais shut down the linked data cloud? On April 1, they reported that:

"As of today (4/1/2015), we are shutting down our existing linked data cloud in order to prepare for the availability of a new linked dataset on April 21. Calls made by the API will resolve to the following URI: http://d.opencalais.com/." See: http://www.opencalais.com/blog

THE DETAILS:

Previously, I had a whole page of categories (such as Technology, Province or state, Organization, Country, etc., etc. etc.) in the Content Type's "Open Calais" tab and in my Taxonomy list.

On April 1, I went into my content types and content, and could only see 3 categories: "Calais Document Category; "Events Facts"; and "Social Tags" in the Open Calais tab. I could still see all of the previous taxonomies in the taxonomy list, though. Needless to say, my content is only being tagged with these 3 categories.

I have tried deleting the taxonomies, re-installing modules, etc., etc. But, still, I only see the 3 categories. I also tried installing/re-installing 7.x-1.0-alpha2 and 7.x-1.x-dev.

And now, I just tried installing ElusiveMind/opencalais. But, I still am getting only 3 categories.

Do you have any idea what the issue could be?

Thanks!
Bobbi

**Comment by ElusiveMind** [comment]
Those three tags are the ones hard-wired into the module to be there regardless. So it is possible you were having problem with the linked data shutdown.

Here is my recommendation:

I have just made some updates to the module which will add the relevant taxonomies if they do not exist at the time the term entities are assigned to a node type. If you don't mind, download the latest 7.x-1.x branch from here on GitHub, go to the OpenCalais Fields tab of the content type and make sure your types are selected. Then press submit and see if that helps.

**Comment by ElusiveMind** [comment]
This issue should now be resolved in the 7.x-1.0 tag of this module.
